"""
Maps every country in the dataset to a geographic sector (region), so the
model classifies images by sector instead of by individual country. This
lets every country's images stay in the training set — a small country
just joins its neighbors' sector — instead of being dropped outright for
having too few images.

Two granularities are provided; SECTOR_GRANULARITY picks which is active.
Switching it (or adding a new mapping to SECTOR_MAPS) is the only change
needed to use more, smaller sectors or fewer, larger ones.
"""

from config import SECTOR_GRANULARITY

COUNTRY_TO_CONTINENT = {
    "Aland": "Europe",
    "Albania": "Europe",
    "American Samoa": "Oceania",
    "Andorra": "Europe",
    "Antarctica": "Antarctica",
    "Argentina": "South America",
    "Armenia": "Asia",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Bangladesh": "Asia",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Bermuda": "North America",
    "Bhutan": "Asia",
    "Bolivia": "South America",
    "Botswana": "Africa",
    "Brazil": "South America",
    "Bulgaria": "Europe",
    "Cambodia": "Asia",
    "Canada": "North America",
    "Chile": "South America",
    "China": "Asia",
    "Colombia": "South America",
    "Costa Rica": "North America",
    "Croatia": "Europe",
    "Curacao": "North America",
    "Czechia": "Europe",
    "Denmark": "Europe",
    "Dominican Republic": "North America",
    "Ecuador": "South America",
    "Egypt": "Africa",
    "Estonia": "Europe",
    "Eswatini": "Africa",
    "Faroe Islands": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Gibraltar": "Europe",
    "Greece": "Europe",
    "Greenland": "North America",
    "Guam": "Oceania",
    "Guatemala": "North America",
    "Hong Kong": "Asia",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Isle of Man": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Japan": "Asia",
    "Jersey": "Europe",
    "Jordan": "Asia",
    "Kenya": "Africa",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Asia",
    "Lesotho": "Africa",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Macao": "Asia",
    "Madagascar": "Africa",
    "Malaysia": "Asia",
    "Malta": "Europe",
    "Martinique": "North America",
    "Mexico": "North America",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Mozambique": "Africa",
    "Myanmar": "Asia",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nigeria": "Africa",
    "North Macedonia": "Europe",
    "Northern Mariana Islands": "Oceania",
    "Norway": "Europe",
    "Pakistan": "Asia",
    "Palestine": "Asia",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "Asia",
    "Pitcairn Islands": "Oceania",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Puerto Rico": "North America",
    "Qatar": "Asia",
    "Reunion": "Africa",
    "Romania": "Europe",
    "Russia": "Europe",
    "San Marino": "Europe",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "South Africa": "Africa",
    "South Georgia and South Sandwich Islands": "Antarctica",
    "South Korea": "Asia",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Svalbard and Jan Mayen": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Taiwan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Tunisia": "Africa",
    "Turkey": "Asia",
    "US Virgin Islands": "North America",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "South America",
    "Venezuela": "South America",
    "Vietnam": "Asia",
}

COUNTRY_TO_SUBREGION = {
    "Aland": "Northern Europe",
    "Albania": "Southern Europe",
    "American Samoa": "Polynesia",
    "Andorra": "Southern Europe",
    "Antarctica": "Antarctica",
    "Argentina": "South America",
    "Armenia": "Western Asia",
    "Australia": "Australia and New Zealand",
    "Austria": "Western Europe",
    "Bangladesh": "Southern Asia",
    "Belarus": "Eastern Europe",
    "Belgium": "Western Europe",
    "Bermuda": "Northern America",
    "Bhutan": "Southern Asia",
    "Bolivia": "South America",
    "Botswana": "Southern Africa",
    "Brazil": "South America",
    "Bulgaria": "Eastern Europe",
    "Cambodia": "South-eastern Asia",
    "Canada": "Northern America",
    "Chile": "South America",
    "China": "Eastern Asia",
    "Colombia": "South America",
    "Costa Rica": "Central America",
    "Croatia": "Southern Europe",
    "Curacao": "Caribbean",
    "Czechia": "Eastern Europe",
    "Denmark": "Northern Europe",
    "Dominican Republic": "Caribbean",
    "Ecuador": "South America",
    "Egypt": "Northern Africa",
    "Estonia": "Northern Europe",
    "Eswatini": "Southern Africa",
    "Faroe Islands": "Northern Europe",
    "Finland": "Northern Europe",
    "France": "Western Europe",
    "Germany": "Western Europe",
    "Ghana": "Western Africa",
    "Gibraltar": "Southern Europe",
    "Greece": "Southern Europe",
    "Greenland": "Northern America",
    "Guam": "Micronesia",
    "Guatemala": "Central America",
    "Hong Kong": "Eastern Asia",
    "Hungary": "Eastern Europe",
    "Iceland": "Northern Europe",
    "India": "Southern Asia",
    "Indonesia": "South-eastern Asia",
    "Iraq": "Western Asia",
    "Ireland": "Northern Europe",
    "Isle of Man": "Northern Europe",
    "Israel": "Western Asia",
    "Italy": "Southern Europe",
    "Japan": "Eastern Asia",
    "Jersey": "Northern Europe",
    "Jordan": "Western Asia",
    "Kenya": "Eastern Africa",
    "Kyrgyzstan": "Central Asia",
    "Laos": "South-eastern Asia",
    "Latvia": "Northern Europe",
    "Lebanon": "Western Asia",
    "Lesotho": "Southern Africa",
    "Lithuania": "Northern Europe",
    "Luxembourg": "Western Europe",
    "Macao": "Eastern Asia",
    "Madagascar": "Eastern Africa",
    "Malaysia": "South-eastern Asia",
    "Malta": "Southern Europe",
    "Martinique": "Caribbean",
    "Mexico": "Central America",
    "Monaco": "Western Europe",
    "Mongolia": "Eastern Asia",
    "Montenegro": "Southern Europe",
    "Mozambique": "Eastern Africa",
    "Myanmar": "South-eastern Asia",
    "Nepal": "Southern Asia",
    "Netherlands": "Western Europe",
    "New Zealand": "Australia and New Zealand",
    "Nigeria": "Western Africa",
    "North Macedonia": "Southern Europe",
    "Northern Mariana Islands": "Micronesia",
    "Norway": "Northern Europe",
    "Pakistan": "Southern Asia",
    "Palestine": "Western Asia",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "South-eastern Asia",
    "Pitcairn Islands": "Polynesia",
    "Poland": "Eastern Europe",
    "Portugal": "Southern Europe",
    "Puerto Rico": "Caribbean",
    "Qatar": "Western Asia",
    "Reunion": "Eastern Africa",
    "Romania": "Eastern Europe",
    "Russia": "Eastern Europe",
    "San Marino": "Southern Europe",
    "Senegal": "Western Africa",
    "Serbia": "Southern Europe",
    "Singapore": "South-eastern Asia",
    "Slovakia": "Eastern Europe",
    "Slovenia": "Southern Europe",
    "South Africa": "Southern Africa",
    "South Georgia and South Sandwich Islands": "Antarctica",
    "South Korea": "Eastern Asia",
    "South Sudan": "Eastern Africa",
    "Spain": "Southern Europe",
    "Sri Lanka": "Southern Asia",
    "Svalbard and Jan Mayen": "Northern Europe",
    "Sweden": "Northern Europe",
    "Switzerland": "Western Europe",
    "Taiwan": "Eastern Asia",
    "Tanzania": "Eastern Africa",
    "Thailand": "South-eastern Asia",
    "Tunisia": "Northern Africa",
    "Turkey": "Western Asia",
    "US Virgin Islands": "Caribbean",
    "Uganda": "Eastern Africa",
    "Ukraine": "Eastern Europe",
    "United Arab Emirates": "Western Asia",
    "United Kingdom": "Northern Europe",
    "United States": "Northern America",
    "Uruguay": "South America",
    "Venezuela": "South America",
    "Vietnam": "South-eastern Asia",
}

SECTOR_MAPS = {
    "continent": COUNTRY_TO_CONTINENT,
    "subregion": COUNTRY_TO_SUBREGION,
}


# Approximate geographic centroids (lat, lon) used for distance-aware
# evaluation. Values are coarse by design and intended for regional scoring,
# not precise geocoding.
CONTINENT_CENTROIDS = {
    "Africa": (1.65, 17.68),
    "Antarctica": (-82.86, 135.00),
    "Asia": (34.05, 100.62),
    "Europe": (54.53, 15.26),
    "North America": (54.53, -105.26),
    "Oceania": (-22.74, 140.75),
    "South America": (-8.78, -55.49),
}

SUBREGION_CENTROIDS = {
    "Antarctica": (-82.86, 135.00),
    "Australia and New Zealand": (-33.86, 144.96),
    "Caribbean": (18.22, -66.59),
    "Central America": (15.20, -88.15),
    "Central Asia": (43.00, 68.00),
    "Eastern Africa": (-3.37, 36.69),
    "Eastern Asia": (35.68, 127.00),
    "Eastern Europe": (50.45, 30.52),
    "Micronesia": (7.45, 151.84),
    "Northern Africa": (30.04, 31.24),
    "Northern America": (44.50, -98.35),
    "Northern Europe": (59.91, 10.75),
    "Polynesia": (-17.68, -149.41),
    "South America": (-15.79, -47.88),
    "South-eastern Asia": (13.75, 100.50),
    "Southern Africa": (-26.20, 28.04),
    "Southern Asia": (28.61, 77.21),
    "Southern Europe": (41.90, 12.50),
    "Western Africa": (14.69, -17.45),
    "Western Asia": (39.93, 32.86),
    "Western Europe": (48.86, 2.35),
}


def get_sector_map():
    """Return the active {country: sector} mapping for SECTOR_GRANULARITY."""
    return SECTOR_MAPS[SECTOR_GRANULARITY]


def get_active_sector_centroids():
    """Return {sector: (lat, lon)} for the active granularity."""
    centroid_maps = {
        "continent": CONTINENT_CENTROIDS,
        "subregion": SUBREGION_CENTROIDS,
    }
    return centroid_maps[SECTOR_GRANULARITY]
